from .._core_exceptions import LograderIOError

class LograderTestError(LograderIOError):
    pass